In [68]:
import numpy as np
import pandas as pd

In [69]:
df=pd.read_csv("Iris_data_sample.csv",index_col=0,na_values=["??","###"])

In [72]:
df.head(5)

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1            5.1           3.5            1.4           0.2  Iris-setosa
2            4.9           NaN            1.4           0.2          NaN
3            4.7           3.2            1.3           0.2  Iris-setosa
4            NaN           3.1            1.5           0.2  Iris-setosa
5            5.0           3.6            NaN           0.2  Iris-setosa

In [73]:

df_txt1=pd.read_table("Iris_data_sample.txt", sep=" ")
df_txt=pd.read_table("Iris_data_sample.txt", delimiter=' ')

In [103]:
df_txt.dtypes

Unnamed: 0         int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [ ]:
cars_data.get_d

In [75]:
cars_data=pd.read_csv("Toyota.csv",index_col=0)

In [76]:

cars_data.head(3)

   Price   Age     KM FuelType  HP  MetColor  Automatic    CC  Doors  Weight
0  13500  23.0  46986   Diesel  90       1.0          0  2000  three    1165
1  13750  23.0  72937   Diesel  90       1.0          0  2000      3    1165
2  13950  24.0  41711   Diesel  90       NaN          0  2000      3    1165

In [77]:
cars_data["Doors"].unique()

array(['three', '3', '5', '4', 'four', 'five', '2'], dtype=object)

In [78]:
cars_data["Doors"].replace("three",3,inplace=True)
cars_data["Doors"].replace("four",4,inplace=True)
cars_data["Doors"].replace("five",5,inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19924\999651106.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data["Doors"].replace("three",3,inplace=True)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19924\999651106.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data["Doors"].replace("four",4,inplace=True)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19924\999651106.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data["Doors"].replace("five",5,inplace=True)

In [66]:
cars_data["Doors"].replace("three",3,inplace=True)
cars_data["Doors"].replace("four",4,inplace=True)
cars_data["Doors"].replace("five",5,inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19924\2532411436.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data["Doors"].replace("3",3,inplace=True)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19924\2532411436.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data["Doors"].replace("4",4,inplace=True)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19924\2532411436.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data["Doors"].replace("5",5,inplace=True)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19924\2532411436.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data["Doors"].replace("2",5,inplace=True)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19924\2532411436.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cars_data["Doors"].replace("2",5,inplace=True)

In [79]:
cars_data["Doors"].unique()

array([3, '3', '5', '4', 4, 5, '2'], dtype=object)

In [81]:
cars_data["Doors"] = cars_data["Doors"].astype(str).astype(int)

In [82]:
cars_data["Doors"].unique()

array([3, 5, 4, 2])

In [83]:
cars_data.columns

Index(['Price', 'Age', 'KM', 'FuelType', 'HP', 'MetColor', 'Automatic', 'CC',
       'Doors', 'Weight'],
      dtype='object')

In [84]:
cars_data.index

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435],
      dtype='int64', length=1436)

In [85]:
cars_data.memory_usage()

Index        11488
Price        11488
Age          11488
KM           11488
FuelType     11488
HP           11488
MetColor     11488
Automatic    11488
CC           11488
Doors        11488
Weight       11488
dtype: int64

In [86]:
cars_data.shape

(1436, 10)

In [87]:
cars_data.size

14360

In [92]:
cars_data.at[12,'FuelType']

'Petrol'

In [98]:
cars_data.iloc[5]

Price         12950
Age            32.0
KM            61000
FuelType     Diesel
HP               90
MetColor        0.0
Automatic         0
CC             2000
Doors             3
Weight         1170
Name: 5, dtype: object

In [96]:
cars_data.iat[1,5]

np.float64(1.0)

In [100]:
cars_data.loc[:,["FuelType","Price"]]

     FuelType  Price
0      Diesel  13500
1      Diesel  13750
2      Diesel  13950
3      Diesel  14950
4      Diesel  13750
...       ...    ...
1431   Petrol   7500
1432   Petrol  10845
1433   Petrol   8500
1434      NaN   7250
1435   Petrol   6950

[1436 rows x 2 columns]

In [104]:
np.where

In [106]:

cars_data.isnull().sum()

Price          0
Age          100
KM             0
FuelType     100
HP             0
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [107]:
cars_data["KM"].astype('category').nbytes

12920

In [108]:
cars_data["KM"].astype('object').nbytes

11488